[package]
name = "mini_sdl"
version = "0.1.5"
edition = "2021"
description = "A small and simple wrapper around SDL2"
license = "MIT"

[dependencies.sdl2]
version = "0.37.0"
default-features = false
features = ["unsafe_textures"]

[workspace]
members = [ "example" ]
