name: SDL_Rust

on:
  push:
  pull_request:

jobs:
  build-linux:
    name: build linux pkg-config
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y libsdl3-dev libsdl3-ttf-dev
          sudo apt-get install libopenal1 libopenal-dev
      - name: Build mini_sdl
        shell: bash
        run: |
          set -xeuo pipefail
          rustc --version
          cargo --version
          cargo build
          cargo test
